name: LD19 Build
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Setup ROS 2
      uses: ros-tooling/setup-ros@0.0.15
      with:
        required-ros-distributions: rolling
    - name: Run Tests
      uses: ros-tooling/action-ros-ci@0.0.13
      with:
        package-name: ld19_lidar
    - name: Upload Logs
      uses: actions/upload-artifact@v1
      with:
        name: colcon-logs
        path: ros_ws/log
      if: always()